/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author AbbiNizar
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        this.setVisible(true);
    }
public void klikKualitas(ActionListener e){
    btnKualitas.addActionListener(e);
}
public void klikPemasaran(ActionListener e){
    btnPemasaran.addActionListener(e);
}
public void klikLaporan(ActionListener e){
    btnLaporan.addActionListener(e);
}
public void klikMitra(ActionListener e){
    btnMitra.addActionListener(e);
}
public void klikPemesanan(ActionListener e){
    btnPemesanan.addActionListener(e);
}
public void klikExit(ActionListener e){
    Exit.addActionListener(e);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPemasaran = new javax.swing.JButton();
        btnKualitas = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnMitra = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPemasaran.setBackground(new Color (0,0,0,0));
        btnPemasaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit Property_104px.png"))); // NOI18N
        btnPemasaran.setBorder(null);
        btnPemasaran.setOpaque(false);
        btnPemasaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemasaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPemasaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 120, 120));

        btnKualitas.setBackground(new Color (0,0,0,0));
        btnKualitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ok_104px.png"))); // NOI18N
        btnKualitas.setBorder(null);
        btnKualitas.setOpaque(false);
        btnKualitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKualitasActionPerformed(evt);
            }
        });
        getContentPane().add(btnKualitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 120, 120));

        btnLaporan.setBackground(new Color (0,0,0,0));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Combo Chart_104px_1.png"))); // NOI18N
        btnLaporan.setBorder(null);
        btnLaporan.setOpaque(false);
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, 120));

        jLabel2.setBackground(new Color (0,0,0,0));
        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Beranda");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 90, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kualitas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mitra Kerja");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 130, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pemasaran");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 120, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pemesanan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 120, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Laporan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 90, -1));

        btnMitra.setBackground(new Color (0,0,0,0));
        btnMitra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Conference Call_104px.png"))); // NOI18N
        getContentPane().add(btnMitra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 130, 120));

        btnPemesanan.setBackground(new Color (0,0,0,0));
        btnPemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Handshake_104px.png"))); // NOI18N
        btnPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemesananActionPerformed(evt);
            }
        });
        getContentPane().add(btnPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 130, 120));

        Exit.setBackground(new Color (0,0,0,0));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shutdown_32px.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPemasaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemasaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPemasaranActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnKualitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKualitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKualitasActionPerformed

    private void btnPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPemesananActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton btnKualitas;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMitra;
    private javax.swing.JButton btnPemasaran;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
