/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author AbbiNizar
 */
public class BerandaPabrik extends javax.swing.JFrame {

    /**
     * Creates new form BerandaPrabik
     */
    public BerandaPabrik() {
        initComponents();
    }
public void klikInformasi(ActionListener e){
    btnInformasi.addActionListener(e);
}
public void klikBelanja(ActionListener e){
    btnBelanja.addActionListener(e);
}
public void klikExit(ActionListener e){
    Exit.addActionListener(e);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnInformasi = new javax.swing.JButton();
        btnBelanja = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setBackground(new Color (0,0,0,0));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shutdown_32px.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 40, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Belanja");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 90, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Informasi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, -1));

        jLabel3.setBackground(new Color (0,0,0,0));
        jLabel3.setFont(new java.awt.Font("Bebas Neue", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Beranda");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 90, 30));

        btnInformasi.setBackground(new Color (0,0,0,0));
        btnInformasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Info Popup_96px.png"))); // NOI18N
        btnInformasi.setMaximumSize(new java.awt.Dimension(105, 105));
        btnInformasi.setMinimumSize(new java.awt.Dimension(105, 105));
        btnInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnInformasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, 110));

        btnBelanja.setBackground(new Color (0,0,0,0));
        btnBelanja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Shopping Cart_96px.png"))); // NOI18N
        btnBelanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBelanjaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBelanja, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 130, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBelanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBelanjaActionPerformed

    private void btnInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformasiActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BerandaPabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BerandaPabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BerandaPabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BerandaPabrik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BerandaPabrik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton btnBelanja;
    private javax.swing.JButton btnInformasi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}

